//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAT.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAT.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Check your input model for the possiblity of errors..
        /// </summary>
        internal static string _1__Check_your_input_model_for_the_possiblity_of_errors_ {
            get {
                return ResourceManager.GetString("_1__Check_your_input_model_for_the_possiblity_of_errors_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Click the Email button to report the error to us..
        /// </summary>
        internal static string _1__Click_the_Email_button_to_report_the_error_to_us_ {
            get {
                return ResourceManager.GetString("_1__Click_the_Email_button_to_report_the_error_to_us_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Click the Continue button to ingore the error..
        /// </summary>
        internal static string _2__Click_the_Continue_button_to_ingore_the_error_ {
            get {
                return ResourceManager.GetString("_2__Click_the_Continue_button_to_ingore_the_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Email us your model and seek for help..
        /// </summary>
        internal static string _2__Email_us_your_model_and_seek_for_help_ {
            get {
                return ResourceManager.GetString("_2__Email_us_your_model_and_seek_for_help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Click the Stop button to exit the application..
        /// </summary>
        internal static string _3__Click_the_Stop_button_to_exit_the_application_ {
            get {
                return ResourceManager.GetString("_3__Click_the_Stop_button_to_exit_the_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Zeno Check Selected.
        /// </summary>
        internal static string Apply_Zeno_Check_Selected {
            get {
                return ResourceManager.GetString("Apply_Zeno_Check_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Zeno Check UnSelected.
        /// </summary>
        internal static string Apply_Zeno_Check_UnSelected {
            get {
                return ResourceManager.GetString("Apply_Zeno_Check_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At same time, you can submit your model to us by using model submit button in the PAT editor..
        /// </summary>
        internal static string At_same_time__you_can_submit_your_model_to_us_by_using_model_submit_button_in_the_PAT_editor_ {
            get {
                return ResourceManager.GetString("At_same_time__you_can_submit_your_model_to_us_by_using_model_submit_button_in_the" +
                        "_PAT_editor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büchi Automata Generated with {0} Nodes {1} Edges (checked in {2} s)..
        /// </summary>
        internal static string Büchi_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2__s__ {
            get {
                return ResourceManager.GetString("Büchi_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2__s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT find the method .
        /// </summary>
        internal static string Can_NOT_find_the_method_ {
            get {
                return ResourceManager.GetString("Can_NOT_find_the_method_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT find the method {0} with {1} parameters in class {2}!.
        /// </summary>
        internal static string Can_NOT_find_the_method__0__with__1__parameters_in_class__2__ {
            get {
                return ResourceManager.GetString("Can_NOT_find_the_method__0__with__1__parameters_in_class__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT find the method {0} with {1} parameters in the imported C# libraries!.
        /// </summary>
        internal static string Can_NOT_find_the_method__0__with__1__parameters_in_the_imported_C__libraries_ {
            get {
                return ResourceManager.GetString("Can_NOT_find_the_method__0__with__1__parameters_in_the_imported_C__libraries_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can not be sent! please manual email the exception to PAT team..
        /// </summary>
        internal static string Email_can_not_be_sent__please_manual_email_the_exception_to_PAT_team_ {
            get {
                return ResourceManager.GetString("Email_can_not_be_sent__please_manual_email_the_exception_to_PAT_team_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is sent successfully..
        /// </summary>
        internal static string Email_is_sent_successfully_ {
            get {
                return ResourceManager.GetString("Email_is_sent_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Happened.
        /// </summary>
        internal static string Error_Happened {
            get {
                return ResourceManager.GetString("Error_Happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Exception happened during the verification.
        /// </summary>
        internal static string Exception_happened_during_the_verification {
            get {
                return ResourceManager.GetString("Exception_happened_during_the_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Result....
        /// </summary>
        internal static string Generating_Result {
            get {
                return ResourceManager.GetString("Generating_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Generated: {0} Nodes, {1} Edges.
        /// </summary>
        internal static string Graph_Generated___0__Nodes___1__Edges {
            get {
                return ResourceManager.GetString("Graph_Generated___0__Nodes___1__Edges", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Knight {
            get {
                object obj = ResourceManager.GetObject("Knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Verification Selected.
        /// </summary>
        internal static string ModelCheckingForm_CheckBox_Parallel_CheckedChanged_Parallel_Verification_Selected {
            get {
                return ResourceManager.GetString("ModelCheckingForm_CheckBox_Parallel_CheckedChanged_Parallel_Verification_Selected" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Verification UnSelected.
        /// </summary>
        internal static string ModelCheckingForm_CheckBox_Parallel_CheckedChanged_Parallel_Verification_UnSelected {
            get {
                return ResourceManager.GetString("ModelCheckingForm_CheckBox_Parallel_CheckedChanged_Parallel_Verification_UnSelect" +
                        "ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Order Reduction Selected.
        /// </summary>
        internal static string ModelCheckingForm_CheckBox_POR_CheckedChanged_Partial_Order_Reduction_Selected {
            get {
                return ResourceManager.GetString("ModelCheckingForm_CheckBox_POR_CheckedChanged_Partial_Order_Reduction_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Order Reduction UnSelected.
        /// </summary>
        internal static string ModelCheckingForm_CheckBox_POR_CheckedChanged_Partial_Order_Reduction_UnSelected {
            get {
                return ResourceManager.GetString("ModelCheckingForm_CheckBox_POR_CheckedChanged_Partial_Order_Reduction_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Starts....
        /// </summary>
        internal static string ModelCheckingForm_StartVerification_Verification_Starts {
            get {
                return ResourceManager.GetString("ModelCheckingForm_StartVerification_Verification_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation is not supported in this module!.
        /// </summary>
        internal static string ModuleFacadeBase_ShowSimulationWindow_Simulation_is_not_supported_in_this_module_ {
            get {
                return ResourceManager.GetString("ModuleFacadeBase_ShowSimulationWindow_Simulation_is_not_supported_in_this_module_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicated state names are allowed!.
        /// </summary>
        internal static string No_duplicated_state_names_are_allowed_ {
            get {
                return ResourceManager.GetString("No_duplicated_state_names_are_allowed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Mode Selected.
        /// </summary>
        internal static string Normal_Mode_Selected {
            get {
                return ResourceManager.GetString("Normal_Mode_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a sequential program or C# method calls can be associated with an event..
        /// </summary>
        internal static string Only_a_sequential_program_or_C__method_calls_can_be_associated_with_an_event_ {
            get {
                return ResourceManager.GetString("Only_a_sequential_program_or_C__method_calls_can_be_associated_with_an_event_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one model checking window can be open at a time! Do you want to close the current one to open a new one?.
        /// </summary>
        internal static string Only_one_model_checking_window_can_be_open_at_a_time__Do_you_want_to_close_the_current_one_to_open_a_new_one_ {
            get {
                return ResourceManager.GetString("Only_one_model_checking_window_can_be_open_at_a_time__Do_you_want_to_close_the_cu" +
                        "rrent_one_to_open_a_new_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input at least one assertion!.
        /// </summary>
        internal static string Please_input_at_least_one_assertion_ {
            get {
                return ResourceManager.GetString("Please_input_at_least_one_assertion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input at least one runnable process (process with no parameters)!.
        /// </summary>
        internal static string Please_input_at_least_one_runnable_process__process_with_no_parameters__ {
            get {
                return ResourceManager.GetString("Please_input_at_least_one_runnable_process__process_with_no_parameters__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row in trace list as the starting point!.
        /// </summary>
        internal static string Please_select_a_row_in_trace_list_as_the_starting_point_ {
            get {
                return ResourceManager.GetString("Please_select_a_row_in_trace_list_as_the_starting_point_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an assertion first!.
        /// </summary>
        internal static string Please_select_an_assertion_first {
            get {
                return ResourceManager.GetString("Please_select_an_assertion_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop verification or parsing before the simulation!.
        /// </summary>
        internal static string Please_stop_verification_or_parsing_before_the_simulation_ {
            get {
                return ResourceManager.GetString("Please_stop_verification_or_parsing_before_the_simulation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop verification or simulation before parsing the model!.
        /// </summary>
        internal static string Please_stop_verification_or_simulation_before_parsing_the_model_ {
            get {
                return ResourceManager.GetString("Please_stop_verification_or_simulation_before_parsing_the_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the simulation or parsing finished before verification.
        /// </summary>
        internal static string Please_wait_for_the_simulation_or_parsing_finished_before_verification {
            get {
                return ResourceManager.GetString("Please_wait_for_the_simulation_or_parsing_finished_before_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the verification to stop first! Otherwise it may cause exceptional behaviors..
        /// </summary>
        internal static string Please_wait_for_the_verification_to_stop_first__Otherwise_it_may_cause_exceptional_behaviors {
            get {
                return ResourceManager.GetString("Please_wait_for_the_verification_to_stop_first__Otherwise_it_may_cause_exceptiona" +
                        "l_behaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabin Automata Generated with {0} Nodes {1} Edges (checked in {2}s)..
        /// </summary>
        internal static string Rabin_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2_s__ {
            get {
                return ResourceManager.GetString("Rabin_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Generation Cancelled.
        /// </summary>
        internal static string Result_Generation_Cancelled {
            get {
                return ResourceManager.GetString("Result_Generation_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Exception Happened.
        /// </summary>
        internal static string Runtime_Exception_Happened {
            get {
                return ResourceManager.GetString("Runtime_Exception_Happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string SampleEnum_Large {
            get {
                return ResourceManager.GetString("SampleEnum_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string SampleEnum_Medium {
            get {
                return ResourceManager.GetString("SampleEnum_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string SampleEnum_Small {
            get {
                return ResourceManager.GetString("SampleEnum_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Large.
        /// </summary>
        internal static string SampleEnum_VeryLarge {
            get {
                return ResourceManager.GetString("SampleEnum_VeryLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Small.
        /// </summary>
        internal static string SampleEnum_VerySmall {
            get {
                return ResourceManager.GetString("SampleEnum_VerySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string Save_File {
            get {
                return ResourceManager.GetString("Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an assertion to start with.
        /// </summary>
        internal static string Select_an_assertion_to_start_with {
            get {
                return ResourceManager.GetString("Select_an_assertion_to_start_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Witness Trace Selected.
        /// </summary>
        internal static string Shortest_Witness_Trace_Selected {
            get {
                return ResourceManager.GetString("Shortest_Witness_Trace_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Witness Trace UnSelected.
        /// </summary>
        internal static string Shortest_Witness_Trace_UnSelected {
            get {
                return ResourceManager.GetString("Shortest_Witness_Trace_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Cancelled.
        /// </summary>
        internal static string Simulation_Cancelled {
            get {
                return ResourceManager.GetString("Simulation_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Starting.
        /// </summary>
        internal static string Simulation_Starting {
            get {
                return ResourceManager.GetString("Simulation_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source State.
        /// </summary>
        internal static string Source_State {
            get {
                return ResourceManager.GetString("Source_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streett Automata Generated with {0} Nodes {1} Edges (checked in {2}s)..
        /// </summary>
        internal static string Streett_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2_s__ {
            get {
                return ResourceManager.GetString("Streett_Automata_Generated_with__0__Nodes__1__Edges__checked_in__2_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target State.
        /// </summary>
        internal static string Target_State {
            get {
                return ResourceManager.GetString("Target_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C# library {0} can not be found!.
        /// </summary>
        internal static string The_C__library__0__can_not_be_found_ {
            get {
                return ResourceManager.GetString("The_C__library__0__can_not_be_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of the step will destroy the current trace. Do you want to continue?.
        /// </summary>
        internal static string The_execution_of_the_step_will_destroy_the_current_trace__Do_you_want_to_continue_ {
            get {
                return ResourceManager.GetString("The_execution_of_the_step_will_destroy_the_current_trace__Do_you_want_to_continue" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression {0} must be a boolean expression!.
        /// </summary>
        internal static string The_expression__0__must_be_a_boolean_expression_ {
            get {
                return ResourceManager.GetString("The_expression__0__must_be_a_boolean_expression_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression {0} must be an integer expression!.
        /// </summary>
        internal static string The_expression__0__must_be_an_integer_expression_ {
            get {
                return ResourceManager.GetString("The_expression__0__must_be_an_integer_expression_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression should return an integer value!.
        /// </summary>
        internal static string The_expression_should_return_an_integer_value_ {
            get {
                return ResourceManager.GetString("The_expression_should_return_an_integer_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formula is a safety property (checked in {0} s)..
        /// </summary>
        internal static string The_formula_is_a_safety_property__checked_in__0__s__ {
            get {
                return ResourceManager.GetString("The_formula_is_a_safety_property__checked_in__0__s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input LTL is not correct: .
        /// </summary>
        internal static string The_input_LTL_is_not_correct__ {
            get {
                return ResourceManager.GetString("The_input_LTL_is_not_correct__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method call {0} must return a boolean value!.
        /// </summary>
        internal static string The_method_call__0__must_return_a_boolean_value_ {
            get {
                return ResourceManager.GetString("The_method_call__0__must_return_a_boolean_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method call {0} must return an integer value!.
        /// </summary>
        internal static string The_method_call__0__must_return_an_integer_value_ {
            get {
                return ResourceManager.GetString("The_method_call__0__must_return_an_integer_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The simulation is forced to stop due to the huge space size ( &gt; {0} states).
        /// </summary>
        internal static string The_simulation_is_forced_to_stop_due_to_the_huge_space_size {
            get {
                return ResourceManager.GetString("The_simulation_is_forced_to_stop_due_to_the_huge_space_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The static method call {0} must return a boolean value!.
        /// </summary>
        internal static string The_static_method_call__0__must_return_a_boolean_value_ {
            get {
                return ResourceManager.GetString("The_static_method_call__0__must_return_a_boolean_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The static method call {0} must return an integer value!.
        /// </summary>
        internal static string The_static_method_call__0__must_return_an_integer_value_ {
            get {
                return ResourceManager.GetString("The_static_method_call__0__must_return_an_integer_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} must be a boolean variable!.
        /// </summary>
        internal static string The_variable__0__must_be_a_boolean_variable_ {
            get {
                return ResourceManager.GetString("The_variable__0__must_be_a_boolean_variable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} must be an integer variable!.
        /// </summary>
        internal static string The_variable__0__must_be_an_integer_variable_ {
            get {
                return ResourceManager.GetString("The_variable__0__must_be_an_integer_variable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. This error suggests your model is too big to be verified. Please make sure all your variables are bounded. You can use domain range values to check it, e.g., &quot;var x:{1..100}=0;&quot;. Alternatively you can simplify your model by using fewer events, simplier processes, and smaller constants and variables..
        /// </summary>
        internal static string This_error_suggests_your_model_is__too_big_to_be_verified_ {
            get {
                return ResourceManager.GetString("This_error_suggests_your_model_is_ too_big_to_be_verified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total transitions visited before the exception:.
        /// </summary>
        internal static string Total_transitions_visited_before_the_exception {
            get {
                return ResourceManager.GetString("Total_transitions_visited_before_the_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Play Finished.
        /// </summary>
        internal static string Trace_Play_Finished {
            get {
                return ResourceManager.GetString("Trace_Play_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Play Starts....
        /// </summary>
        internal static string Trace_Play_Starts___ {
            get {
                return ResourceManager.GetString("Trace_Play_Starts___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Play Stopped.
        /// </summary>
        internal static string Trace_Play_Stopped {
            get {
                return ResourceManager.GetString("Trace_Play_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables ({0}) can not be used in this expression .
        /// </summary>
        internal static string Variables___0___can_not_be_used_in_this_expression_ {
            get {
                return ResourceManager.GetString("Variables___0___can_not_be_used_in_this_expression_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Mode Selected.
        /// </summary>
        internal static string Verbose_Mode_Selected {
            get {
                return ResourceManager.GetString("Verbose_Mode_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Cancelled.
        /// </summary>
        internal static string Verification_Cancelled {
            get {
                return ResourceManager.GetString("Verification_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Completed.
        /// </summary>
        internal static string Verification_Completed {
            get {
                return ResourceManager.GetString("Verification_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification has been running for {0} s.
        /// </summary>
        internal static string Verification_has_been_running_for__0__s {
            get {
                return ResourceManager.GetString("Verification_has_been_running_for__0__s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have following options:.
        /// </summary>
        internal static string You_have_following_options_ {
            get {
                return ResourceManager.GetString("You_have_following_options_", resourceCulture);
            }
        }
    }
}
